a=int(input("Enter Number1:")) 
b=int(input("Enter Number2:"))
print("Addition      :",a+b)
print("Subtraction   :",a-b)
print("Multiplication:",a*b)
print("Division      :",a/b)
print("Modulus       :",a%b)
print("Exponentiation:",a**b)
print("Floor division:",a//b)
